// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: submit.proto

package submit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubmitRPCService_UpdateSubmit_FullMethodName = "/submit.SubmitRPCService/UpdateSubmit"
)

// SubmitRPCServiceClient is the client API for SubmitRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubmitRPCServiceClient interface {
	UpdateSubmit(ctx context.Context, in *UpdateSubmitRequest, opts ...grpc.CallOption) (*UpdateSubmitResponse, error)
}

type submitRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubmitRPCServiceClient(cc grpc.ClientConnInterface) SubmitRPCServiceClient {
	return &submitRPCServiceClient{cc}
}

func (c *submitRPCServiceClient) UpdateSubmit(ctx context.Context, in *UpdateSubmitRequest, opts ...grpc.CallOption) (*UpdateSubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubmitResponse)
	err := c.cc.Invoke(ctx, SubmitRPCService_UpdateSubmit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubmitRPCServiceServer is the server API for SubmitRPCService service.
// All implementations must embed UnimplementedSubmitRPCServiceServer
// for forward compatibility.
type SubmitRPCServiceServer interface {
	UpdateSubmit(context.Context, *UpdateSubmitRequest) (*UpdateSubmitResponse, error)
	mustEmbedUnimplementedSubmitRPCServiceServer()
}

// UnimplementedSubmitRPCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubmitRPCServiceServer struct{}

func (UnimplementedSubmitRPCServiceServer) UpdateSubmit(context.Context, *UpdateSubmitRequest) (*UpdateSubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubmit not implemented")
}
func (UnimplementedSubmitRPCServiceServer) mustEmbedUnimplementedSubmitRPCServiceServer() {}
func (UnimplementedSubmitRPCServiceServer) testEmbeddedByValue()                          {}

// UnsafeSubmitRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubmitRPCServiceServer will
// result in compilation errors.
type UnsafeSubmitRPCServiceServer interface {
	mustEmbedUnimplementedSubmitRPCServiceServer()
}

func RegisterSubmitRPCServiceServer(s grpc.ServiceRegistrar, srv SubmitRPCServiceServer) {
	// If the following call pancis, it indicates UnimplementedSubmitRPCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubmitRPCService_ServiceDesc, srv)
}

func _SubmitRPCService_UpdateSubmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmitRPCServiceServer).UpdateSubmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubmitRPCService_UpdateSubmit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmitRPCServiceServer).UpdateSubmit(ctx, req.(*UpdateSubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubmitRPCService_ServiceDesc is the grpc.ServiceDesc for SubmitRPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubmitRPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "submit.SubmitRPCService",
	HandlerType: (*SubmitRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateSubmit",
			Handler:    _SubmitRPCService_UpdateSubmit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "submit.proto",
}
