run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/iviuser

  errcheck:
    check-type-assertions: true
    check-blank: true

  staticcheck:
    checks: ["all"]