services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iviuser
      MYSQL_USER: iviuser
      MYSQL_PASSWORD: iviuser

  app:
    image: ividernvi/iviuser:latest
    environment:
      - IVIUSER_MYSQL_HOSTNAME=db
      - IVIUSER_MINIO_ENDPOINT=minio:9000
      - IVIUSER_REDIS_HOSTNAME=redis:6379
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - db
      - minio