// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: solution.proto

package solution

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SolutionRPCService_GetSolution_FullMethodName = "/solution.SolutionRPCService/GetSolution"
)

// SolutionRPCServiceClient is the client API for SolutionRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolutionRPCServiceClient interface {
	GetSolution(ctx context.Context, in *GetSolutionRequest, opts ...grpc.CallOption) (*GetSolutionResponse, error)
}

type solutionRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSolutionRPCServiceClient(cc grpc.ClientConnInterface) SolutionRPCServiceClient {
	return &solutionRPCServiceClient{cc}
}

func (c *solutionRPCServiceClient) GetSolution(ctx context.Context, in *GetSolutionRequest, opts ...grpc.CallOption) (*GetSolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSolutionResponse)
	err := c.cc.Invoke(ctx, SolutionRPCService_GetSolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolutionRPCServiceServer is the server API for SolutionRPCService service.
// All implementations must embed UnimplementedSolutionRPCServiceServer
// for forward compatibility.
type SolutionRPCServiceServer interface {
	GetSolution(context.Context, *GetSolutionRequest) (*GetSolutionResponse, error)
	mustEmbedUnimplementedSolutionRPCServiceServer()
}

// UnimplementedSolutionRPCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSolutionRPCServiceServer struct{}

func (UnimplementedSolutionRPCServiceServer) GetSolution(context.Context, *GetSolutionRequest) (*GetSolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSolution not implemented")
}
func (UnimplementedSolutionRPCServiceServer) mustEmbedUnimplementedSolutionRPCServiceServer() {}
func (UnimplementedSolutionRPCServiceServer) testEmbeddedByValue()                            {}

// UnsafeSolutionRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolutionRPCServiceServer will
// result in compilation errors.
type UnsafeSolutionRPCServiceServer interface {
	mustEmbedUnimplementedSolutionRPCServiceServer()
}

func RegisterSolutionRPCServiceServer(s grpc.ServiceRegistrar, srv SolutionRPCServiceServer) {
	// If the following call pancis, it indicates UnimplementedSolutionRPCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SolutionRPCService_ServiceDesc, srv)
}

func _SolutionRPCService_GetSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolutionRPCServiceServer).GetSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolutionRPCService_GetSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolutionRPCServiceServer).GetSolution(ctx, req.(*GetSolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SolutionRPCService_ServiceDesc is the grpc.ServiceDesc for SolutionRPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolutionRPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "solution.SolutionRPCService",
	HandlerType: (*SolutionRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSolution",
			Handler:    _SolutionRPCService_GetSolution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "solution.proto",
}
